name: 'Test Pipeline'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        include:
        - node_dir: "I am cool"
          node: "dev"
        - node_dir: "I am not cool"
          node: "prod"
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Show Dev
      if: ${{ matrix.node_dir }} == "dev"
      run: |
        echo ${{ matrix.node_dir }}
        echo ${{ secrets.SECRET_1 }}
        
    - name: Show Prod
      if: ${{ matrix.node_dir }} == "prod"
      run: |
        echo ${{ matrix.node_dir }}
        echo ${{ secrets.SECRET_2 }}
