name: 'Test Pipeline'

on:
  push:
    branches:
    - main

jobs:
  make-file:
    runs-on: ubuntu-latest
    name: Make NPMRC File
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Modules
        run: |
          echo "${{ secrets.NPMRC }}" > frontend/.npmrc
          cat frontend/.npmrc

  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        include:
        - node_dir: "I am cool"
          node: SECRET_1
        - node_dir: "I am not cool"
          node: SECRET_2
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Show Information
      run: |
        echo ${{ matrix.node_dir }}
        echo ${{ secrets[matrix.node] }}
