name: 'Test Pipeline'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        include:
        - node_dir: "I am cool"
          node: ${{ secrets.SECRET_1 }}
        - node_dir: "I am not cool"
          node: ${{ secrets.SECRET_2 }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Show environment v2
      run: |
        echo ${{ matrix.node_dir }}
        echo ${{ matrix.node }}
